global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'vector'
    static_configs:
      - targets: ['192.168.1.xxx:9598']  # ← Vector コンテナ名とポートに合わせて
    metrics_path: /metrics
    scheme: http
